---
title: "Introduction to phyloGLM"
author: "Noah Dukler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

First create some data and a tree. Pretend that sites are split into two classes, "Enhancer" and "Promoter" and also split by ontology classes "A" and "B".

```{r}
library(phyloGLM)
## Set seed for consistency
set.seed(123)
## Simulate random data
species=c("A","B","C","D","E")
aData=lapply(as.list(species),function(x) matrix(runif(120),ncol=3))
names(aData)=species

## Create test trees, both one that will fail, and one that will pass
tree=ape::rtree(n = length(species),tip.label = species)

## Create a data frame with labels
siteLabels=data.frame(cre.class=rep(c("Enhancer","Promoter"),each=nrow(aData[[1]])/2),
                      go.class=rep(c("A","B"),times=nrow(aData[[1]])/2))
```
Now create the allele data object:

```{r,echo=FALSE}
ad=alleleData(data=aData,tree=tree,siteInfo = siteLabels)
```

Now create a rate model specifying that genomic regions should be seperated by both cre.class and go.class.

```{r}
rateMod=rateModel(data = ad,rateFormula=formula(~cre.class+go.class))
```

Now we can fit the model:

```{r}
# fit(rateMod)
failP=c(1.072339241,0.996833310,0.999776478,-2.463222270,-4.021448349,0.004552635,-6.568507110,-5.444297674,-4.300386918)
rateMod@phylogeny$setParams(failP,1:length(failP)-1)
siteLL(rateMod,40)
zoo=numeric(40); for(i in 1:40) zoo[i]=rateMod@phylogeny$rate(0,rateMod@rateDM[i,,drop=FALSE])
zooPi=matrix(nrow=40,ncol=3); for(i in 1:40) zooPi[i,]=rateMod@phylogeny$pi(rateMod@piDM[i,,drop=FALSE])
for(i in 1:length(tree$edge.length)) print(rateMod@phylogeny$rateMatrix(zooPi[22,],zoo[22],tree$edge.length[i]))
```


```{r}
tempM=matrix(c(-1.5658e+005,8.3997e+000,1.5657e+005,
  1.2882e-002,-1.5657e+005,1.5657e+005,
  1.2882e-002,8.3997e+000,-8.4126e+000),byrow=TRUE,ncol=3,nrow=3)
expm::expm(tempM)
## Compute e^A with svd
eigen(tempM)
s=svd(tempM)
s$u%*%exp(diag(s$d))%*%t(s$v)
data.table::fwrite(as.data.frame(tempM),"../../../../Downloads/fail_matrix.txt",row.names = FALSE,col.names = FALSE)
```

