# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expokit_dgpadm <- function(mat, t, transpose) {
    .Call(`_phyloGLM_expokit_dgpadm`, mat, t, transpose)
}

#' Vector logSumExpArma
#'
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
NULL

#' Vector logSumExp
#' 
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
#' @export
logSumExp <- function(x) {
    .Call(`_phyloGLM_logSumExp`, x)
}

#' matrixToStlPointer
#' 
#' This function converts a matrix to a 2D double stl vector and returns a XPtr to a 
#' pointer to the vector
#'
#' @param x A numeric matrix
#' @export
matrixToStlXptr <- function(x) {
    .Call(`_phyloGLM_matrixToStlXptr`, x)
}

#' @export
stlMatrixSubset <- function(xpsexp, row, col) {
    .Call(`_phyloGLM_stlMatrixSubset`, xpsexp, row, col)
}

