# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Vector logSumExpArma
#'
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
NULL

#' Vector logSumExp
#' 
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
#' @export
logSumExp <- function(x) {
    .Call(`_phyloGLM_logSumExp`, x)
}

